import { UILang } from "../langsState";

/* ===== 多言語辞書 ===== */
export type Keys =
  | "home"
  | "menuTitle"
  | "projects" // ★ 追加：旧 products（イベント に変更）
  | "products" // ★ 新設：商品一覧
  | "productsEC" // EC
  | "staffs"
  | "pricing"
  | "areas"
  | "stores"
  | "story"
  | "blog"
  | "news"
  | "company"
  | "reserve"
  | "contact"
  | "partners"
  | "timeline"
  | "community"
  | "analytics"
  | "admin"
  | "aiChat"
  | "hours";

export const T: Record<UILang, Record<Keys, string>> = {
  ja: {
    menuTitle: "メニュー",
    home: "ホーム",
    projects: "イベント",
    products: "商品一覧",
    productsEC: "オンラインショップ",
    staffs: "スタッフ",
    pricing: "ご案内",
    areas: "対応エリア",
    stores: "店舗一覧",
    story: "私たちの思い",
    blog: "ブログ",
    news: "お知らせ",
    company: "会社概要",
    reserve: "ご予約はこちら",
    contact: "お問い合わせ",
    partners: "協力業者募集！",
    timeline: "タイムライン",
    community: "コミュニティ",
    analytics: "分析",
    admin: "管理者ログイン",
    aiChat: "AIサポート",
    hours: "営業時間",
  },
  en: {
    menuTitle: "Menu",
    home: "Home",
    projects: "Events",
    products: "Products",
    productsEC: "Online Store",
    staffs: "Staff",
    pricing: "Information",
    areas: "Service Areas",
    stores: "Store List",
    story: "Our Story",
    blog: "Blog",
    news: "News",
    company: "Company Profile",
    reserve: "Book Here",
    contact: "Contact",
    partners: "Partner Contractors Wanted!",
    timeline: "Timeline",
    community: "Community",
    analytics: "Analytics",
    admin: "Administrator Login",
    aiChat: "AI Chat",
    hours: "Hours",
  },
  zh: {
    menuTitle: "菜单",
    home: "首页",
    projects: "活动",
    products: "商品一览",
    productsEC: "网店",
    staffs: "员工",
    pricing: "服务指南",
    areas: "服务区域",
    stores: "门店列表",
    story: "我们的理念",
    blog: "博客",
    news: "公告",
    company: "公司简介",
    reserve: "点击预约",
    contact: "联系我们",
    partners: "招募合作业者！",
    timeline: "时间线",
    community: "社区",
    analytics: "分析",
    admin: "管理员登录",
    aiChat: "AI聊天",
    hours: "营业时间",
  },
  "zh-TW": {
    menuTitle: "選單",
    home: "首頁",
    projects: "活動",
    products: "商品一覽",
    productsEC: "網路商店",
    staffs: "員工",
    pricing: "服務指南",
    areas: "服務範圍",
    stores: "門市列表",
    story: "我們的理念",
    blog: "部落格",
    news: "最新消息",
    company: "公司簡介",
    reserve: "預約請點此",
    contact: "聯絡我們",
    partners: "招募合作廠商！",
    timeline: "時間軸",
    community: "社群",
    analytics: "分析",
    admin: "管理者登入",
    aiChat: "AI聊天",
    hours: "營業時間",
  },
  ko: {
    menuTitle: "메뉴",
    home: "홈",
    projects: "이벤트",
    products: "상품 목록",
    productsEC: "온라인 스토어",
    staffs: "스태프",
    pricing: "안내",
    areas: "서비스 지역",
    stores: "매장 목록",
    story: "우리의 이야기",
    blog: "블로그",
    news: "공지사항",
    company: "회사 소개",
    reserve: "예약하기",
    contact: "문의하기",
    partners: "협력 업체 모집!",
    timeline: "타임라인",
    community: "커뮤니티",
    analytics: "분석",
    admin: "관리자 로그인",
    aiChat: "AI 채팅",
    hours: "영업시간",
  },
  fr: {
    menuTitle: "Menu",
    home: "Accueil",
    projects: "Événements",
    products: "Produits",
    productsEC: "Boutique en ligne",
    staffs: "Équipe",
    pricing: "Informations",
    areas: "Zones desservies",
    stores: "Liste des magasins",
    story: "Notre histoire",
    blog: "Blog",
    news: "Actualités",
    company: "Profil de l’entreprise",
    reserve: "Réserver ici",
    contact: "Contact",
    partners: "Partenaires recherchés !",
    timeline: "Timeline",
    community: "Communauté",
    analytics: "Analyses",
    admin: "Connexion administrateur",
    aiChat: "Chat IA",
    hours: "Horaires",
  },
  es: {
    menuTitle: "Menú",
    home: "Inicio",
    projects: "Eventos",
    products: "Productos",
    productsEC: "Tienda en línea",
    staffs: "Equipo",
    pricing: "Información",
    areas: "Áreas de servicio",
    stores: "Lista de tiendas",
    story: "Nuestra historia",
    blog: "Blog",
    news: "Noticias",
    company: "Perfil de la empresa",
    reserve: "Reservar aquí",
    contact: "Contacto",
    partners: "¡Buscamos colaboradores!",
    timeline: "Cronología",
    community: "Comunidad",
    analytics: "Analítica",
    admin: "Inicio de sesión de administrador",
    aiChat: "Chat IA",
    hours: "Horario",
  },
  de: {
    menuTitle: "Menü",
    home: "Startseite",
    projects: "Veranstaltungen",
    products: "Produkte",
    productsEC: "Online-Shop",
    staffs: "Team",
    pricing: "Informationen",
    areas: "Einsatzgebiete",
    stores: "Filialübersicht",
    story: "Unsere Geschichte",
    blog: "Blog",
    news: "Neuigkeiten",
    company: "Unternehmensprofil",
    reserve: "Hier buchen",
    contact: "Kontakt",
    partners: "Partner gesucht!",
    timeline: "Timeline",
    community: "Community",
    analytics: "Analytik",
    admin: "Administrator-Anmeldung",
    aiChat: "AI-Chat",
    hours: "Öffnungszeiten",
  },
  pt: {
    menuTitle: "Menu",
    home: "Início",
    projects: "Eventos",
    products: "Produtos",
    productsEC: "Loja Online",
    staffs: "Equipe",
    pricing: "Informações",
    areas: "Áreas de atendimento",
    stores: "Lista de lojas",
    story: "Nossa história",
    blog: "Blog",
    news: "Notícias",
    company: "Perfil da empresa",
    reserve: "Reservar aqui",
    contact: "Contato",
    partners: "Procuramos parceiros!",
    timeline: "Linha do tempo",
    community: "Comunidade",
    analytics: "Análises",
    admin: "Login do administrador",
    aiChat: "Chat IA",
    hours: "Horário",
  },
  it: {
    menuTitle: "Menu",
    home: "Home",
    projects: "Eventi",
    products: "Prodotti",
    productsEC: "Negozio online",
    staffs: "Staff",
    pricing: "Informazioni",
    areas: "Aree servite",
    stores: "Elenco negozi",
    story: "La nostra storia",
    blog: "Blog",
    news: "Notizie",
    company: "Profilo aziendale",
    reserve: "Prenota qui",
    contact: "Contatto",
    partners: "Cercasi partner!",
    timeline: "Timeline",
    community: "Community",
    analytics: "Analitiche",
    admin: "Accesso amministratore",
    aiChat: "Chat IA",
    hours: "Orari",
  },
  ru: {
    menuTitle: "Меню",
    home: "Главная",
    projects: "События",
    products: "Товары",
    productsEC: "Интернет-магазин",
    staffs: "Сотрудники",
    pricing: "Информация",
    areas: "Районы обслуживания",
    stores: "Список магазинов",
    story: "Наша история",
    blog: "Блог",
    news: "Новости",
    company: "О компании",
    reserve: "Онлайн-запись",
    contact: "Контакты",
    partners: "Ищем парнёров-подрядчиков!",
    timeline: "Лента",
    community: "Сообщество",
    analytics: "Аналитика",
    admin: "Вход администратора",
    aiChat: "AI-чат",
    hours: "Часы работы",
  },
  th: {
    menuTitle: "เมนู",
    home: "หน้าแรก",
    projects: "กิจกรรม",
    products: "รายการสินค้า",
    productsEC: "ร้านค้าออนไลน์",
    staffs: "ทีมงาน",
    pricing: "ข้อมูล",
    areas: "พื้นที่ให้บริการ",
    stores: "รายชื่อร้านค้า",
    story: "เรื่องราวของเรา",
    blog: "บล็อก",
    news: "ข่าวสาร",
    company: "ข้อมูลบริษัท",
    reserve: "จองที่นี่",
    contact: "ติดต่อเรา",
    partners: "รับสมัครพันธมิตร!",
    timeline: "ไทม์ไลน์",
    community: "คอมมูนิตี้",
    analytics: "วิเคราะห์",
    admin: "เข้าสู่ระบบผู้ดูแล",
    aiChat: "แชต AI",
    hours: "เวลาเปิดทำการ",
  },
  vi: {
    menuTitle: "Menu",
    home: "Trang chủ",
    projects: "Sự kiện",
    products: "Sản phẩm",
    productsEC: "Cửa hàng trực tuyến",
    staffs: "Nhân viên",
    pricing: "Thông tin",
    areas: "Khu vực phục vụ",
    stores: "Danh sách cửa hàng",
    story: "Câu chuyện của chúng tôi",
    blog: "Blog",
    news: "Tin tức",
    company: "Hồ sơ công ty",
    reserve: "Đặt lịch tại đây",
    contact: "Liên hệ",
    partners: "Tuyển đối tác!",
    timeline: "Dòng thời gian",
    community: "Cộng đồng",
    analytics: "Phân tích",
    admin: "Đăng nhập quản trị",
    aiChat: "Trò chuyện AI",
    hours: "Giờ làm việc",
  },
  id: {
    menuTitle: "Menu",
    home: "Beranda",
    projects: "Acara",
    products: "Produk",
    productsEC: "Toko daring",
    staffs: "Staf",
    pricing: "Informasi",
    areas: "Area layanan",
    stores: "Daftar toko",
    story: "Kisah kami",
    blog: "Blog",
    news: "Berita",
    company: "Profil perusahaan",
    reserve: "Pesan di sini",
    contact: "Kontak",
    partners: "Mencari mitra!",
    timeline: "Linimasa",
    community: "Komunitas",
    analytics: "Analitik",
    admin: "Masuk admin",
    aiChat: "Obrolan AI",
    hours: "Jam operasional",
  },
  hi: {
    menuTitle: "मेनू",
    home: "होम",
    projects: "कार्यक्रम",
    products: "उत्पाद",
    productsEC: "ऑनलाइन स्टोर",
    staffs: "स्टाफ़",
    pricing: "जानकारी",
    areas: "सेवा क्षेत्र",
    stores: "स्टोर सूची",
    story: "हमारी कहानी",
    blog: "ब्लॉग",
    news: "समाचार",
    company: "कंपनी प्रोफ़ाइल",
    reserve: "यहाँ बुक करें",
    contact: "संपर्क करें",
    partners: "सहयोगी ठेकेदार आमंत्रित!",
    timeline: "टाइमलाइन",
    community: "समुदाय",
    analytics: "विश्लेषण",
    admin: "प्रशासक लॉगिन",
    aiChat: "AI चैट",
    hours: "समय",
  },
  ar: {
    menuTitle: "القائمة",
    home: "الصفحة الرئيسية",
    projects: "الفعاليات",
    products: "قائمة المنتجات",
    productsEC: "المتجر الإلكتروني",
    staffs: "الفريق",
    pricing: "معلومات",
    areas: "مناطق الخدمة",
    stores: "قائمة المتاجر",
    story: "قصتنا",
    blog: "المدونة",
    news: "الأخبار",
    company: "نبذة عن الشركة",
    reserve: "احجز هنا",
    contact: "اتصل بنا",
    partners: "نبحث عن شركاء!",
    timeline: "الخط الزمني",
    community: "المجتمع",
    analytics: "التحليلات",
    admin: "تسجيل دخول المسؤول",
    aiChat: "دردشة الذكاء الاصطناعي",
    hours: "ساعات العمل",
  },
};
